---
title: "Bombus population genomics"
output: plot_protein_and_stacked_barchart.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

1. Load libraries:

```{r, message = FALSE}
require(ggplot2)
require(ggpubr)
```

2. Read in input files for gene model:

```{r, message = FALSE}
## Read in file for plotting:
data <- read.table(file = "input/input_for_plot_domains.txt",
                   header = TRUE)
colnames(data)

protein_domain <- ggplot(data, aes(xmin = start,
                         xmax = end,
                         y = protein)) +
        facet_wrap(~ protein,
                   scales = "free",
                   ncol = 1) +
        geom_gene_arrow(arrowhead_height = unit(3, "mm"),
                        arrowhead_width = unit(1, "mm")) +
        geom_subgene_arrow(data = data,
                           aes(xmin = start,
                               xmax = end,
                               y = protein,
                               fill = domain,
                               xsubmin = start_domain,
                               xsubmax = end_domain),
                           color = "black",
                           alpha = .7) +
        theme_genes() +
        theme(axis.ticks = element_blank(),
              axis.title.y = element_blank(),
              axis.text = element_blank(),
              axis.ticks.x = element_blank(),
              axis.line.x = element_blank(),
              legend.position = "none")

## Update colours for plotting:
protein_domain <- protein_domain +
        scale_fill_manual(name = "Functional domains",
                          values = c("yellow",
                                     "blue")) +
        theme(plot.margin = grid::unit(c(0, 0, 0, 0), "mm"))
```

3. Read in input files for stacked barchart:

```{r, message = FALSE}
sequence_1_info <- read.table(file = "input/group_counts/sequence_one_count_modified.txt",
                              header = TRUE)

## The second column ('group') contains words joined by underscores.
## For plotting, replace underscores with spaces.
sequence_1_info$group <- gsub(pattern = "_",
                              replacement = " ",
                              sequence_1_info$group)

## Update levels for plotting:
sequence_1_info$group <- factor(sequence_1_info$group,
                                   levels = unique(sequence_1_info$group))

sequence_1_info$status <- "section_1"

sequence_2_info <- read.table(file = "input/group_counts/sequence_two_count_modified.txt",
                              header = TRUE)

## The second column ('group') contains words joined by underscores.
## For plotting, replace underscores with spaces.
sequence_2_info$group <- gsub(pattern = "_",
                              replacement = " ",
                              sequence_2_info$group)

## Update levels for plotting:
sequence_2_info$group <- factor(sequence_2_info$group,
                                levels = unique(sequence_2_info$group))

sequence_2_info$status <- "section_2"

sequence_3_info <- read.table(file = "input/group_counts/sequence_three_count_modified.txt",
                              header = TRUE)

## The second column ('group') contains words joined by underscores.
## For plotting, replace underscores with spaces.
sequence_3_info$group <- gsub(pattern = "_",
                              replacement = " ",
                              sequence_3_info$group)

## Update levels for plotting:
sequence_3_info$group <- factor(sequence_3_info$group,
                                levels = unique(sequence_3_info$group))

sequence_3_info$status <- "section_3"

sequence_4_info <- read.table(file = "input/group_counts/sequence_four_count_modified.txt",
                              header = TRUE)

## The second column ('group') contains words joined by underscores.
## For plotting, replace underscores with spaces.
sequence_4_info$group <- gsub(pattern = "_",
                              replacement = " ",
                              sequence_4_info$group)

## Update levels for plotting:
sequence_4_info$group <- factor(sequence_4_info$group,
                                levels = unique(sequence_4_info$group))

sequence_4_info$status <- "section_4"

## Combine:
combined_df <- as.data.frame(rbind(sequence_1_info,
                    sequence_2_info,
                    sequence_3_info,
                    sequence_4_info))

## Update status:
combined_df$status <- gsub(pattern = "_",
                           replacement = " ",
                           combined_df$status)

# Stacked
stacked_barchart <- ggplot(combined_df,
                           aes(fill = group,
                               y = count,
                               x = status)) +
        xlab("Protein subsections (aa)") +
        ylab("BLASTP matches") +
        geom_bar(position = "stack",
                 stat = "identity") +
        scale_fill_manual(name = "Taxonomic\ngroup",
                          values = c("steelblue1",
                                    "light blue",
                                     "blue",
                                     "navy",
                                     "orange",
                                     "grey",
                                     "black")) +
        theme_bw() +
        theme(axis.title = element_text(size = 12,
                                        face = "bold"),
              axis.text = element_text(size = 10,
                                       face = "plain"),
              legend.title = element_text(size = 10,
                                          face = "bold"),
              legend.position = "bottom")
```

4. Generate a combined plot:

```{r, message = FALSE}
combined_domains <- ggarrange(protein_domain,
                              stacked_barchart,
                              ncol = 1,
                              nrow = 2,
                              heights = c(0.5,
                                          2),
                              align = "hv")
```

5. Save image:

```{r, message = FALSE}
## Output plot to file:
ggsave(file = "results/protein_domain_barchart.png",
       height = 6,
       width = 10)

## Save everything as R object:
save.image(file = ".results/protein_domain_plus_stackedchart.RData")
```

6. Run lintr:

```{r, message = FALSE}
lintr::lint(file = "plot_protein_and_stacked_barchart.Rmd")
```
