---
title: "Bombus population genomics"
output: ibd_plot.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script loads an R object and plots a correlation plot of values estimated through an 'identity-by-descent' (IBD) analysis. The output is a saved .png image.

```{r, message = FALSE}
## Load R object:
load( file = "./results/pca_plots.Rdata")
```

Generate correlation plot:

```{r, message = FALSE}
require(ggplot2)
require(reshape2)
## Updated column names:
colnames(input_for_melt) <- as.character(unlist(new_names))
rownames(input_for_melt) <- as.character(unlist(new_names))
input_for_melt_melted <- melt(input_for_melt)

## Generate plot:
ibs_plot <- ggplot(data = input_for_melt_melted,
               aes(x = Var1,
                   y = Var2,
                   fill = value)) +
        xlab("Samples") +
        ylab("Samples") +
        geom_tile(colour = "black") +
        theme(axis.text.x = element_text(angle = 90,
                                         hjust = 1),
              axis.title = element_text(size = 15,
                                      face = "bold")) +
        scale_fill_gradient(low = "yellow", high = "black") +
        theme(axis.title = element_blank())

ibs_plot <- ibs_plot + guides(fill = guide_legend(title = "r value"))

summary(input_for_melt_melted$value)

## Print to console:
ibs_plot

## Save image:
ggsave(file = "results/ibs_correlation_plot.png",
       height = 10,
       width = 10)

## Plot IBD kinship coefficients:
ibd_coeff_mle_fo_melt <- ibd_coeff_mle[, c(1, 2, 6)]

## Update the name of samples for plotting:
new_id1 <- vector()
new_id2 <- vector()
## Create a list:
for (name in 1:length(ibd_coeff_mle_fo_melt$ID1)){
        new_id1[name] <- paste(strsplit(ibd_coeff_mle_fo_melt$ID1[name], "_")[[1]][5],
        "_", strsplit(ibd_coeff_mle_fo_melt$ID1[name], "_")[[1]][6],
        sep = "")
}
## Create a list:
for (name in 1:length(ibd_coeff_mle_fo_melt$ID2)){
        new_id2[name] <- paste(strsplit(ibd_coeff_mle_fo_melt$ID2[name], "_")[[1]][5],
        "_", strsplit(ibd_coeff_mle_fo_melt$ID2[name], "_")[[1]][6],
        sep = "")
}
## Update names:
ibd_coeff_mle_fo_melt$ID1 <- new_id1
ibd_coeff_mle_fo_melt$ID2 <- new_id2

ibd_coeff_mle_fo_melted <- melt(ibd_coeff_mle_fo_melt)
ibd_coeff_mle_fo_melted$variable <- NULL

## Transform into factors and update levels:
ibd_coeff_mle_fo_melted$ID1 <- factor(ibd_coeff_mle_fo_melted$ID1, levels = (unique(ibd_coeff_mle_fo_melted$ID1)))

ibd_coeff_mle_fo_melted$ID2 <- factor(ibd_coeff_mle_fo_melted$ID2, levels = (unique(ibd_coeff_mle_fo_melted$ID2)))

## Generate plot:
kinship_plot <- ggplot(data = ibd_coeff_mle_fo_melted,
               aes(x = ID1,
                   y = ID2,
                   fill = value)) +
        xlab("Samples") +
        ylab("Samples") +
        geom_tile(colour = "black") +
        theme(axis.text.x = element_text(angle = 90,
                                         hjust = 1),
              axis.title = element_text(size = 15,
                                      face = "bold")) +
        scale_fill_gradient(low = "yellow", high = "black") +
        theme(axis.title = element_blank())

kinship_plot <- kinship_plot +
        guides(fill = guide_legend(title = "kinship coefficient")) 

levels(ibd_coeff_mle_fo_melted$value)

levels(ibd_coeff_mle_fo_melted$ID1) <- sample_id_sorted_by_ascending_latitude$sample.id

levels(ibd_coeff_mle_fo_melted$ID2) <- sample_id_sorted_by_ascending_latitude$sample.id

## Save to file:
ggsave(file = "./results/kinship_matrix.png",
       height = 10,
       width = 10)
```

Generate a combined plot:

```{r, message = FALSE}
## Generate a combined plot:
require(ggpubr)
ggarrange(ibs_plot,
          kinship_plot,
          ncol = 1,
          nrow = 2,
          labels = c("A", "B"),
          align = "hv")

## Save plot:
ggsave(file = "./results/combined_IBS_IBD.png",
       height = 12,
       width = 10)
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "./ibd_plot.Rmd")
```
