---
title: "Bombus population genomics"
output: calculate_zscores_gene_density.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE)
        }
}

## Create output folder:
dir.create(path = "./results/figures",
           recursive = TRUE)
```

Read in input data:

```{r, message = FALSE}
## Read in input file:
data <- read.table(file = "./input/gene_density_200kb_plus_coordinates.txt",
                   header = FALSE)

## Updated column names:
colnames(data) <- c("position",
                    "gene_density")

## Calculate z-score for gene density:
data_gene_density_sd <- sd(data$gene_density) *
                 sqrt((length(data$gene_density) - 1) /
                              (length(data$gene_density)))
data_gene_density_mean <- mean(data$gene_density)

data$gene_density_zscores <- (data$gene_density - data_gene_density_mean) / 
                              data_gene_density_sd
data$gene_density_pvalue2sided <- 2 * pnorm(-abs(data$gene_density_zscores))

summary(data$gene_density_pvalue2sided)
summary(data$gene_density)

## Subset based on significant:
data_sig <- subset(data,
                   gene_density_pvalue2sided < 0.05)
```

Write the output to file:

```{r, message = FALSE}
## Turn off scientific notation:
options(scipen = 999)

## write to output
write.table(x = data,
            file = "./results/gene_density_zscore_normalised.txt",
            row.names = FALSE,
            col.names = TRUE,
            quote = FALSE,
            sep = "\t")
```

Subset regions with significant high or low nucleotide diversity:

```{r, message = FALSE}
## Save output:
save(data, file = "./results/zscore_normalised.Rdata")
```
Run lintr

```{r, message = FALSE}
lintr::lint(file = "./calculate_zscores.Rmd")
```
