---
title: "2018-07-06_suppl_pca_plots"
author: "JoeColgan"
date: "6 July 2018"
output: html_document
---

```{r}
## Plot PCA of larger number of samples (n=46):
## Assign the input name:  
input_n46_vcf <- "n46_samples/freebayes_hap0_minQ_1_minaltfrac_0.25_minCov1.Bter_n46.NC_only.minQ20.snps_only.no_hets.sites_low_freq.maxmissing1.0.rare_variants_removed.recode.vcf"

## Convert VCF to genome data structure (gds) file format
## gds is a container for storing annotation data and SNP genotypes.
## In this format, each byte encodes up to four SNP genotypes thereby reducing file size and access time.
## The GDS format supports data blocking so that only the subset of data that is being processed needs
## to reside in memory. GDS formatted data is also designed for efficient data access to large datasets.

## Use the name of input to designate the name for the GDS file format.
input_n46_vcf_gds <- gsub(".vcf", ".gds", input_n46_vcf)

## Reformat VCF into GDS format
snpgdsVCF2GDS(input_n46_vcf, input_n46_vcf_gds, method="biallelic.only")

## Extract genotype information:
input_n46_vcf_gds_genofile <- snpgdsOpen(input_n46_vcf_gds)

## Extract genotype information and generate genotypic matrix:  
input_n46_vcf_gds_genofile_matrix <- read.gdsn(index.gdsn(input_n46_vcf_gds_genofile, "genotype"))

## Perform PCA and store output in variable:  
pca_n46      <- snpgdsPCA(input_n46_vcf_gds_genofile, num.thread=2, autosome.only=FALSE)

## Calculate percentages for principal components:  
pc_percent_n46      <- pca_n46$varprop*100
## Print rounded up percentages:  
print(round(pc_percent_n46, 2))

## Extract sample names from input:  
sample_id_n46     <- read.gdsn(index.gdsn(input_n46_vcf_gds_genofile, "sample.id"))

## Read in file containing treatment information. 
## This file should contain 'treatment information' for each sample and be in the same order as each sample. 
## i.e. the first treatment information would be assigned to the first sample, etc., etc.
## Read in table:
pop_code_n46_df <- read.table(file = "n46_samples/landuse_site_info_n46.txt",
                          header = FALSE)

## Rename columns:
colnames(pop_code_n46_df) <- c("sample", "site_number", "landuse")

##
pop_code_n46 <- pop_code_n46_df$landuse

## Generate a dataframe containing a column for:
## 1) Sample name
## 2) Treatment condition
## 3) First principal component of interest
## 4) Second principal component of interest
tab_n46 <- data.frame(sample.id = pca_n46$sample.id,
                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                  EV1 = pca_n46$eigenvect[,1],    # the first eigenvector
                  EV2 = pca_n46$eigenvect[,2],    # the second eigenvector
                  stringsAsFactors = FALSE)

## Rename the samples for plotting:  
## Renaming the sample.ids
new_names <- list()

## Create a list:
for (name in sample_id_n46){
        new_names[name] <- paste(strsplit(name, "_")[[1]][5],"_",strsplit(name, "_")[[1]][6], sep="")
}

## Unlist as a character string and update sample ids:
tab_n46$sample.id <- as.character(unlist(new_names))

## Add another column for site_id:
tab_n46$site_id <- pop_code_n46_df$site_number

## Check status of whether there are two or one individual per site:
new_site_id <- vector()

for (i in 1:length(tab_n46$site_id)){
        status <- duplicated(tab_n46$site_id)[i]
        if (status==FALSE){
                print("Not duplicated")
                new_site_id <- c(new_site_id, paste(tab_n46$site_id[i], "A", sep=""))
        }
        else {
                print("Duplicated")
                new_site_id <- c(new_site_id, paste(tab_n46$site_id[i], "B", sep=""))
        }
}

## Write samples to file:
#write(new_site_id, file="sample_names.txt", sep="\t")

## Update site information: 
tab_n46$site_id <- new_site_id

## Alternatively, to plot with just sample ids and not points:
names_n46_plot<- ggplot(tab_n46, aes(x=tab_n46$EV1, y=tab_n46$EV2, color = tab_n46$pop)) +
        #geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
        theme_minimal() +
        xlab(paste("Principal component", 1," ","(",round(pc_percent_n46[1], 2), "%", ")", sep="")) +
        ylab(paste("Principal component", 2," ","(",round(pc_percent_n46[2], 2), "%", ")", sep="")) + 
        geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
        scale_color_manual(values= c("blue", "orange", "red"))

## Adjust the size of the labels:
names_n46_plot <- names_n46_plot +
                 theme(axis.text=element_text(size=20),
                 axis.title=element_text(size=20,face="bold")) +
                 theme(legend.position="none")

## Plot:
names_n46_plot

## Plot together:
ggarrange(names_n46_plot, 
          names_plot,
          ncol=2, nrow=1,
          labels = c("A", "B"))

```

We want a means to cycle through the first four principal components:

```{r}
## Define function for plotting principal components:
plot_pcomponents <- function(component_one, component_two, component_three, component_four){
                  tab_n46 <- data.frame(sample.id = pca_n46$sample.id,
                                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                                  EV1 = pca_n46$eigenvect[,component_one],    # the first eigenvector
                                  EV2 = pca_n46$eigenvect[,component_two],    # the second eigenvector
                                  stringsAsFactors = FALSE)
                  print(tab_n46)
                  
                                names_n46_plot<- ggplot(tab_n46, aes(x=tab_n46$EV1, y=tab_n46$EV2, color = tab_n46$pop)) +
                                   geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
                                        theme_minimal() +
                                        xlab(paste("Principal component", component_one," ","(",round(pc_percent_n46[component_one], 2), "%", ")", sep="")) +
                                        ylab(paste("Principal component", component_two," ","(",round(pc_percent_n46[component_two], 2), "%", ")", sep="")) + 
                                        #geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
                                        scale_color_manual(values= c("blue", "orange", "red"))
                                
                                ## Adjust the size of the labels:
                                names_n46_plot <- names_n46_plot +
                                                 theme(axis.text=element_text(size=15),
                                                 axis.title=element_text(size=15,face="bold")) +
                                                 theme(legend.position="none")
                                
                                print(names_n46_plot)
                                
                                ## SECOND PLOT:
                                tab_n46_2 <- data.frame(sample.id = pca_n46$sample.id,
                                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                                  EV1 = pca_n46$eigenvect[,component_one],    # the first eigenvector
                                  EV2 = pca_n46$eigenvect[,component_three],    # the second eigenvector
                                  stringsAsFactors = FALSE)
                  print(tab_n46)
                  
                                names_n46_plot_2 <- ggplot(tab_n46_2, 
                                                           aes(x=tab_n46_2$EV1, 
                                                               y=tab_n46_2$EV2, 
                                                               color = tab_n46_2$pop)) +
                                   geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
                                        theme_minimal() +
                                        xlab(paste("Principal component", component_one," ","(",round(pc_percent_n46[component_one], 2), "%", ")", sep="")) +
                                        ylab(paste("Principal component", component_three," ","(",round(pc_percent_n46[component_three], 2), "%", ")", sep="")) + 
                                        #geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
                                        scale_color_manual(values= c("blue", "orange", "red"))
                                
                                ## Adjust the size of the labels:
                                names_n46_plot_2 <- names_n46_plot_2 +
                                                 theme(axis.text=element_text(size=15),
                                                 axis.title=element_text(size=15,face="bold")) +
                                                 theme(legend.position="none")
                                
                                ## Print to console:
                                print(names_n46_plot_2)
                                ggarrange(names_n46_plot, names_n46_plot_2)
                                
                                ## THIRD PLOT:
                                tab_n46_3 <- data.frame(sample.id = pca_n46$sample.id,
                                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                                  EV1 = pca_n46$eigenvect[,component_one],    # the first eigenvector
                                  EV2 = pca_n46$eigenvect[,component_four],    # the second eigenvector
                                  stringsAsFactors = FALSE)

                                names_n46_plot_3 <- ggplot(tab_n46_3, 
                                                           aes(x=tab_n46_3$EV1, 
                                                               y=tab_n46_3$EV2, 
                                                               color = tab_n46_3$pop)) +
                                   geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
                                        theme_minimal() +
                                        xlab(paste("Principal component", component_one," ","(",round(pc_percent_n46[component_one], 2), "%", ")", sep="")) +
                                        ylab(paste("Principal component", component_four," ","(",round(pc_percent_n46[component_four], 2), "%", ")", sep="")) + 
                                        #geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
                                        scale_color_manual(values= c("blue", "orange", "red"))
                                
                                ## Adjust the size of the labels:
                                names_n46_plot_3 <- names_n46_plot_3 +
                                                 theme(axis.text=element_text(size=15),
                                                 axis.title=element_text(size=15,face="bold")) +
                                                 theme(legend.position="none")
                        
                                
                                ## FOURTH PLOT:
                                tab_n46_4 <- data.frame(sample.id = pca_n46$sample.id,
                                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                                  EV1 = pca_n46$eigenvect[,component_two],    # the first eigenvector
                                  EV2 = pca_n46$eigenvect[,component_three],    # the second eigenvector
                                  stringsAsFactors = FALSE)
                  
                                names_n46_plot_4 <- ggplot(tab_n46_4, 
                                                           aes(x=tab_n46_4$EV1, 
                                                               y=tab_n46_4$EV2, 
                                                               color = tab_n46_4$pop)) +
                                   geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
                                        theme_minimal() +
                                        xlab(paste("Principal component", component_two," ","(",round(pc_percent_n46[component_two], 2), "%", ")", sep="")) +
                                        ylab(paste("Principal component", component_three," ","(",round(pc_percent_n46[component_three], 2), "%", ")", sep="")) + 
                                        #geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
                                        scale_color_manual(values= c("blue", "orange", "red"))
                                
                                ## Adjust the size of the labels:
                                names_n46_plot_4 <- names_n46_plot_4 +
                                                 theme(axis.text=element_text(size=15),
                                                 axis.title=element_text(size=15,face="bold")) +
                                                 theme(legend.position="none")
                                
                                ## Print to console:
                                print(names_n46_plot_4)
                                
                                ## FIFTH PLOT:
                                tab_n46_5 <- data.frame(sample.id = pca_n46$sample.id,
                                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                                  EV1 = pca_n46$eigenvect[,component_two],    # the first eigenvector
                                  EV2 = pca_n46$eigenvect[,component_four],    # the second eigenvector
                                  stringsAsFactors = FALSE)
                  
                                names_n46_plot_5 <- ggplot(tab_n46_5, 
                                                           aes(x=tab_n46_5$EV1, 
                                                               y=tab_n46_5$EV2, 
                                                               color = tab_n46_5$pop)) +
                                   geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
                                        theme_minimal() +
                                        xlab(paste("Principal component", component_two," ","(",round(pc_percent_n46[component_two], 2), "%", ")", sep="")) +
                                        ylab(paste("Principal component", component_four," ","(",round(pc_percent_n46[component_four], 2), "%", ")", sep="")) + 
                                        #geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
                                        scale_color_manual(values= c("blue", "orange", "red"))
                                
                                ## Adjust the size of the labels:
                                names_n46_plot_5 <- names_n46_plot_5 +
                                                 theme(axis.text=element_text(size=15),
                                                 axis.title=element_text(size=15,face="bold")) +
                                                 theme(legend.position="none")
                                
                                ## SIXTH PLOT:
                                tab_n46_6 <- data.frame(sample.id = pca_n46$sample.id,
                                  pop = factor(pop_code_n46)[match(pca_n46$sample.id, sample_id_n46)],
                                  EV1 = pca_n46$eigenvect[,component_three],    # the first eigenvector
                                  EV2 = pca_n46$eigenvect[,component_four],    # the second eigenvector
                                  stringsAsFactors = FALSE)
                  
                                names_n46_plot_6 <- ggplot(tab_n46_4, 
                                                           aes(x=tab_n46_6$EV1, 
                                                               y=tab_n46_6$EV2, 
                                                               color = tab_n46_6$pop)) +
                                   geom_point(shape=16, size=4, alpha=0.4, show.legend = T) +
                                        theme_minimal() +
                                        xlab(paste("Principal component", component_three," ","(",round(pc_percent_n46[component_three], 2), "%", ")", sep="")) +
                                        ylab(paste("Principal component", component_four," ","(",round(pc_percent_n46[component_four], 2), "%", ")", sep="")) + 
                                        #geom_text(size=6, position=position_jitter(width=0.04, height=0.04), aes(label=tab_n46$site_id, color=tab_n46$pop)) +
                                        scale_color_manual(values= c("blue", "orange", "red"))
                                
                                ## Adjust the size of the labels:
                                names_n46_plot_6 <- names_n46_plot_6 +
                                                 theme(axis.text=element_text(size=15),
                                                 axis.title=element_text(size=15,face="bold")) +
                                                 theme(legend.position="none")
                                
                                ## Combined plot:
                                ggarrange(names_n46_plot, names_n46_plot_2,
                                          names_n46_plot_3, names_n46_plot_4,
                                          names_n46_plot_5, names_n46_plot_6,
                                          nrow=3, ncol = 2,
                                          labels = c("A", "B", "C", "D", "E", "F"))

}

## Call function:
plot_pcomponents(1,2,3,4)

```
