---
title: "Bombus population genomics"
output: multi_plot_figure_4.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script takes two R objects containing multi-image plots:
1) Nucleotide diversity estimates for _Bombus terrestris_  
2) Nucleotide diversity estimates for _Apis mellifera_  
And generates a combined plot, which is then output in .png and .pdf format.  

1. Load libraries:  

```{r, message = FALSE}
## Load libraries:
libraries <- c("ggplot2",
               "SNPRelate",
               "reshape2",
               "ggpubr",
               "stringr",
               "gggenes")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE)
        }
}
```

2. Load R objects:

```{r, message = FALSE}
## Load arrow plot:
load(file = "results/combined_apis_plots.RData")
load(file = "results/plots/large_sweep_chrom_one_combined_plot.Rdata.Rdata")
```

3. Combine bter and amel plots:

```{r, message = FALSE}
## Generate a combined plot with honeybee plots:
apidae_chrom_1 <- ggarrange(bter_combined,
                            combined_apis_plot,
                            nrow = 2,
                            ncol = 1,
                            heights = c(1.5,
                                        0.8),
                            align = "hv")

## Save as PDF:
ggsave(file = "results/figure_4_combined.pdf",
       dpi = 600,
       width = 13,
       height = 14)

## Save as PNG:
ggsave(file = "results/figure_4_combined.png",
       width = 13,
       height = 14)

## Save as an R object:
save.image(file = "results/multi_image_plot_chrom_one.RData")
```

4. Run lintr:

```{r, message = FALSE}
lintr::lint(file = "multi_plot_figure_4.Rmd")
```
