---
title: "plot_bee_ideograms"
author: "JoeColgan"
date: "15/6/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("karyoploteR")
library(karyoploteR)

custom.genome <- toGRanges(data.frame(chr = c("Bter_chrom_1",
                                              "Amel_chrom_1"),
                                      start=c(1, 1),
                                      end=c(17153651, 29893408)))

kp <- plotKaryotype(genome = custom.genome)
dev.off()
kpAddBaseNumbers(kp)

kp <- plotKaryotype(chromosomes="chr8", plot.type = 2)
kpAddBaseNumbers(kp, tick.dist = 10000000, tick.len = 10, tick.col="red", cex=1,
                 minor.tick.dist = 1000000, minor.tick.len = 5, minor.tick.col = "gray")

```

What we want is two rectanges indicating chromosome one for both <i>Bombus terrestris</i> and <i>Apis mellifera</i>.

```{r, message = FALSE}
## Create a dataframe
chromosomes = data.frame(bter_x = c(1.45,1.55),
                         amel_x = c(1.5,1.6),
                         bter_y = c(1,2),
                         amel_y = c(17153651, 29893408),
                         species = c("bumblebee", "honeybee"),
                         r = c("Bombus terrestris Chr one",
                               "Apis mellifera Chr one"))

## Syntenic region of interest:
first_region = data.frame(first_region_x = c(1.5, 1.55),
                          first_region_y_a = c(362267, 22255080),
                          first_region_y_b = c(438609, 22342791))
second_region <- data.frame(x = c(1.5, 1.5, 1.55, 1.55),
                     y = c(
                           439177,
                           450665,
                           28315047,
                           28312737),
                         species = c(rep("bumblebee",2),
                                     rep("honeybee",2)))
third_region <- data.frame(x = c(1.5, 1.5, 1.55, 1.55),
                     y = c(450609,
                           560366,
                           27056241,
                           27146426),
                      species = c(rep("bter",2),
                                     rep("amel",2)))


## Plot using ggplot2:
p <- ggplot() +
        #scale_x_continuous(name = "x") + 
        #scale_y_continuous(name = "y") +
        xlim(1.3,1.8) +
        ylim(0, 29893408) +
        geom_rect(data = chromosomes,
                  mapping = aes(xmin = bter_x,
                                xmax = amel_x,
                                ymin = bter_y,
                                ymax = amel_y,
                                fill = species),
                  color = "black", alpha = 0.5) +
        #geom_text(data = chromosomes,
        #          aes(x = bter_x + 
        #                      (amel_x - bter_x)/2,
        #              y = bter_y + 
        #                      (amel_y - bter_y)/2, label = r),
        #          size = 4) +
        geom_line(data = first_region,
                  mapping = aes(x = first_region_x,
                                y = first_region_y_a),
                  alpha = 0.5,
                  linetype = "dashed") +
        geom_line(data = second_region,
                  mapping = aes(x = x,
                                y = y),
                  alpha = 0.5,
                  linetype = "dashed") +
        geom_line(data = third_region,
                  mapping = aes(x = x,
                                y = y),
                  alpha = 0.5,
                  linetype = "dashed") +
        scale_fill_manual(values = c("white", "grey")) +
        theme_clear() +
        theme(axis.line = element_blank(),
              axis.text.x = element_blank(),
              axis.text.y = element_blank(),
              axis.ticks = element_blank(),
              axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              legend.position = "top",
              panel.background = element_blank(),
              panel.border = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              plot.background = element_blank())
```
