
```{r}
## Load libraries:
library(ggplot2)
library(rphylopic)
library(EBImage)
```

```{r}
## Create data:
data <- as.character(c(1:10))

exposure <- as.character(c(rep(1.5,4), rep(1.5,6)))

control <- as.character(rep(1,10))

## Create dataframe:
data_df <- as.data.frame(cbind(data,exposure, control))

## update column names:
colnames(data_df) <- c("Days", "Exposure", "Control")

##
insect <- name_search('Bombus terrestris')[[1]]
bumblebee <- name_search(text = "Bombus terrestris", options = "namebankID")[[1]]
img <- image_data("750eeb4f-7ca5-49ff-a814-27a12d0cb13a", size = "1024")[[1]]


## Reorder levels:
levels(data_df$Days)<- factor(sort(as.numeric(levels(data_df$Days))))

##
plot <- ggplot(data=data_df, aes(x=Days, y = Exposure)) +
        geom_point(size=0.5, colour = "red") +
        #ylim(c(0,3)) +
        #geom_smooth() +
        geom_hline(yintercept = 1, 
                   size= 1,
                   linetype="dotted", 
                   colour="blue") +
        geom_hline(yintercept = 2, 
                   size= 1,
                   linetype="dotted", 
                   colour="red") +
        geom_vline(xintercept = 6, 
                   size= 1,
                   linetype="dotted", 
                   colour="black") +
        geom_point(data= data_df, aes(x=Days, y = Control), size=0.5, colour = "blue") +
        geom_rect(data=NULL,aes(xmin=0,xmax=6,ymin=-Inf,ymax=Inf),
                    fill="light blue", alpha=0.05)+
  geom_rect(data=NULL,aes(xmin=6,xmax=10,ymin=-Inf,ymax=Inf),
                    fill="pink", alpha=0.05)+
        theme_minimal() +
        theme(axis.text = element_text(size = 15, face= "bold"),
              axis.title.x = element_text(size = 15, face = "bold"),
              axis.text.y = element_blank(), 
              axis.title.y =  element_text(size = 15, face = "bold"))

#for (i in 1:10){
plot <- plot + add_phylopic(img, 1, x=10, y=1, color="steelblue", ysize = 1) 
plot <- plot + add_phylopic(img, 1, x=10, y=2, color="red", ysize = 1)

#plot <- plot + add_phylopic(img, 1, x=10, y=2, color="orange", ysize = 1.5)

plot <- plot + add_phylopic(img, 1, x=0.5, y=1, color="steelblue", ysize = 0.75) 
plot <- plot + add_phylopic(img, 1, x=0.5, y=2, color="steelblue", ysize = 0.75)

plot <- plot + add_phylopic(img, 1, x=6, y=1, color="steelblue", ysize = 0.75) 
plot <- plot + add_phylopic(img, 1, x=6, y=2, color="red", ysize = 0.75)

plot <- plot + annotate("rect", xmin = 5, xmax = 7, ymin = 2.25, ymax = 2.5, colour="black", fill="white")

plot <- plot + annotate("text", x = 6, y = 2.375, label = "Start of exposure period")

plot <- plot + annotate("rect", xmin = 9, xmax = 11, ymin = 2.25, ymax = 2.5, colour="black", fill="white")

plot <- plot + annotate("text", x = 10, y = 2.375, label = "End of exposure period")

plot <- plot + annotate("rect", xmin = 0, xmax = 2, ymin = 1.175, ymax = 1.375, colour="black", fill="white")

plot <- plot + annotate("text", x = 1, y = 1.25, label = "Control", colour = "blue")

plot <- plot + annotate("rect", xmin = 0, xmax = 2, ymin = 2.25, ymax = 2.5, colour="black", fill="white")

plot <- plot + annotate("text", x = 1, y = 2.375, label = "Neonicotinoid treatment", colour = "red")

## Print to console:
plot

```
