---
title: "Bombus population genomics"
output: calculate_zscores_nsl.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:  
This script calculate z-scores values for |nsl| scores.  
It takes |nsl| scores per snps (calculated by selscan) as input.  
It outputs a tab-delimited text file as well as saves calculations as an R object.  

1. Load libraries:

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE)
        }
}

## Create output folder:
dir.create(path = "./results/figures",
           recursive = TRUE)
```

2. Read in input data:

```{r, message = FALSE}
## Read in input file:
data <- read.table(file = "./input/combined_all_nsl_annotated_snps_n46_snp_positions.annotated.txt",
                   header = FALSE)

## Updated column names:
colnames(data) <- c("chrom",
                    "position",
                    "nsl_score",
                    "annotation")

## Calculate z-score for nsl:
data_nsl_sd <- sd(data$nsl_score) *
                 sqrt((length(data$nsl_score) - 1) /
                              (length(data$nsl_score)))
data_nsl_mean <- mean(data$nsl_score)

data$nsl_zscores <- (data$nsl_score - data_nsl_mean) / data_nsl_sd
data$nsl_pvalue2sided <- 2 * pnorm(-abs(data$nsl_zscores))

## Subset based on threshold of significance:
data_sig <- subset(x = data,
                   nsl_score > 2.56)
nrow(data_sig)
summary(data_sig$nsl_score)
summary(data_sig$nsl_zscores)
```

3. Write the output to file as well as save as R object:  

```{r, message = FALSE}
## Turn off scientific notation:
options(scipen = 999)

## write to output
write.table(x = data,
            file = "./results/zscore_normalised.txt",
            row.names = FALSE,
            col.names = TRUE,
            quote = FALSE,
            sep = "\t")

## Save as R output:
save(data, file = "./results/zscore_normalised.Rdata")
```

4. Run lintr  

```{r, message = FALSE}
lintr::lint(file = "./calculate_zscores.Rmd")
```
