---
title: "Bombus population genomics"
output: generate_count_table.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:  
The purpose of this script is to take an R object containing gene-levels TPM counts as estimated by [tximport](https://bioconductor.org/packages/release/bioc/html/tximport.html), convert to a dataframe and output as a text file.

```{r, message = FALSE}
## Load R object:
load(file = "input/txi_count_estimates.Rdata")
```

Extract count table:

```{r, message = FALSE}
## Convert count matrix into a dataframe:
counts_df <- as.data.frame(txi_counts$counts)
```

Save to file:

```{r, message = FALSE}
## Create output directory:
dir.create(path = "results")

## Write table to file:
write.table(x = counts_df,
            file = "results/wolbachia_count_table.txt",
            col.names = TRUE,
            row.names = FALSE,
            quote = FALSE,
            sep = "\t")
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "generate_count_table.Rmd")
```
