---
title: "Bombus population genomics"
output: admixture_plot.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script takes the output Q-Scores from ADMIXTURE and plots.  

1. Load libraries:  

```{r, message=FALSE}
## Load libraries; install from scratch if needed
libraries <- c("ggpubr", "ggplot2", "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE )
    }
}
```

2. Read in data:

```{r, message=FALSE}
## Read in table:
admix_pop <- read.table("./freebayes_hap0_minQ_1_minaltfrac_0.25_minCov1.Bter_n46.NC_only.minQ20.snps_only.no_hets.sites_low_freq.rare_variants_free.maxMeanDP100.recode.ann.vcf.plink.5.Q")
```

3. Generate plot:  

```{r, message = FALSE}
## generate a barpot using ggplot2:
admix_pop35_cor <- cor(admix_pop35)

col<- colorRampPalette(c("blue", "white", "red", "yellow", "green"))(20)
heatmap(x = admix_pop35_cor,
        col = col,
        symm = TRUE)
```
