---
title: "Bombus population genomics"
output: combine_map_pca_plot.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script loads R objects containing:
1) A map of Britain detailing collection sites (highlighted by latitude);
2) A principal component analysis of sites (highlighted by landuse type)
3) A principal component analysis of sites (highlighted by latitude)

```{r, message = FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2",
               "ggpubr",
               "ggrepel",
               "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE)
    }
}
## Create output directory:
dir.create("results")
```
Next step is to load input files (R objects)

```{r, message = FALSE}
## Load objects:
load(file = "./results/map_of_britain.Rdata")
load(file = "./input/pca_plot/pca_plots.Rdata")
load(file = "./results/manhattan_plot.RData")
load(file = "./results/figures/combined_go_terms_barchart.Rdata")
load(file = "./results/histogram_snp_by_variant_type.Rdata")

## Read in data:
data_points <- read.csv(file = "input/map_input/input_for_maps.csv",
                        header = TRUE)

britain_map <- britain_map +
        theme_bw() +
        theme(legend.position = "none",
              axis.text = element_text(size = 10,
                  face = "plain"),
              axis.title = element_text(size = 15,
                  face = "bold"))

## Update latitude plot with points:
lat_plot <- ggplot(tab,
            aes(x = tab$EV1,
                y = tab$EV2)) +
            xlab(paste("Principal component",
                       1,
                       " ",
                       "(",
                       round(pc_percent[1],
                             2), "%", ")",
                       sep = "")) +
            ylab(paste("Principal component",
                       2,
                       " ",
                       "(",
                       round(pc_percent[2],
                             2), "%", ")",
                       sep = "")) +
        geom_point(size = 5,
                aes(color = latitude,
                    fill = latitude)) +
        geom_label_repel(aes(label = site_id)) +
        theme_minimal() +
            theme(axis.text = element_text(size = 10,
                  face = "plain"),
                  axis.title = element_text(size = 15,
                  face = "bold")) +
            theme(legend.position = "none")

## Perform correlation test:
cor.test(tab$EV2,
         tab$latitude,
         methd = "pearson")

## Update latitude plot with points:
lat_correlation <- ggplot(tab,
            aes(x = tab$EV2,
                y = tab$latitude)) +
            xlab(paste("Principal component",
                       2,
                       " ",
                       "(",
                       round(pc_percent[2],
                             2), "%", ")",
                       sep = "")) +
            ylab("Latitude (°N)") +
        geom_point(size = 5,
                aes(color = latitude,
                    fill = latitude)) +
        geom_label_repel(aes(label = site_id)) +
        theme_minimal() +
            theme(axis.text = element_text(size = 10,
                  face = "plain"),
                  axis.title = element_text(size = 15,
                  face = "bold")) +
            theme(legend.position = "none")

## Perform correlation test:
cor.test(tab$EV2,
         tab$latitude)

## Annotate plot with results from cor.test
lat_correlation <- lat_correlation +
        annotate(geom = "text",
                           y = 55.5,
                           x = -0.15,
                           label = "r = 0.75",
                 size = 5) +
        annotate(geom = "text",
                           y = 55.2,
                           x = -0.15,
                           label = "p < 1e-08",
                 size = 5)

ggsave(file = "./results/correlation_latitude.png",
       height = 8,
       width = 10)

## Combine and plot together:
map_plot <- ggarrange(britain_map,
          lat_plot,
          ncol = 2,
          nrow = 1,
          align = "hv",
          widths = c(1, 1),
          labels = c("A", "B"))

variant_plot <- ggarrange(manhattan_plot,
          variant_histogram,
          ncol = 1,
          nrow = 2,
          align = "hv",
          widths = c(1, 1),
          labels = c("C", "D"))

plot_2 <- ggarrange(variant_plot,
          combined_terms_plot,
          ncol = 2,
          nrow = 1,
          labels = c("C",
                     "E"))

plot_3 <- ggarrange(map_plot,
          plot_2,
          ncol = 1,
          nrow = 2,
          heights = c(0.75, 1)
          )

## Save combined plot to file:
ggsave(file = "./results/figure_1_map_plus_pca_plus_manhattan.png",
        width = 13,
        height = 16)

## Save as PDF:
ggsave(file = "./results/figure_1_map_plus_pca.pdf",
       dpi = 600,
        width = 13,
        height = 16)
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "./multi_plot_figure_1.Rmd")
```
