---
title: "Bombus population genomics"
output: plot_global_sweeps.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE )
        }
}

## Create output folder:
dir.create(path = "./results/figures",
           recursive = TRUE)

```

Read in input data:

```{r, message = FALSE}
## Read in input file:
data <- read.table(file = "./input/nsl_output/combined_nsl_input_for_calculating_top_one.txt",
                       col.names = c("chrom",
                                     "position",
                                     "redundant_position",
                                     "nsl_score"))
snps_highlight <- subset(data,
                         nsl_score > 2.56)

## Generate a facet plot:
p <- ggplot(data, aes(position, nsl_score)) + 
        geom_point(colour = "black",
                           size = 1,
                           alpha = 0.5) +
        geom_hline(yintercept = c(2.56),
                   linetype = "dashed",
                   colour = "orange") +
        geom_point(data = snps_highlight, 
                           aes(x = position,
                               y = nsl_score),
                           colour = "red",
                           size = 1,
                           alpha = 0.5) +
        theme_bw()

p + facet_wrap( ~ chrom, ncol = 2)

ggsave(file = "results/combined_nsl_acrpss_chromomes.png",
       width = 10,
       height = 10)
```

Explore genomic regions with significant proportion of SNPs with strong signatures of LD:

```{r, message=FALSE}
## Read in input file containing positions of SNPs:
snp_info <- read.table(file = "input/nsl_output/snps_in_nsl_n41_unfiltered.sig.txt",
                       col.names = c("chrom",
                                     "position",
                                     "redundant_position",
                                     "nsl_score"))
## Turn off scientific notation:
options(scipen = 999)

## Generate a facet plot:
q <- ggplot(data, aes(position, nsl_score)) + 
        xlab("Genomic coordinates (bp)") +
        ylab("|nsl| score") +
        geom_point(colour = "grey",
                           size = 1,
                           alpha = 0.3) +
        geom_hline(yintercept = c(2.56),
                   linetype = "dashed",
                   colour = "orange") +
        geom_point(data = snp_info, 
                           aes(x = position,
                               y = nsl_score),
                           colour = "black",
                           size = 1,
                           alpha = 0.5) +
        theme_bw() +
        theme(axis.text = element_text(size = 15),
              axis.title.x = element_text(size = 15,
                                          face = "bold"),
              axis.title.y = element_text(size = 15,
                                          face = "bold"),
              axis.text.y = element_text(size = 12,
                                         face = "bold"),
              axis.text.x = element_text(size = 12))

## Print to console:
q + facet_wrap( ~ chrom, ncol = 2)

ggsave(file = "results/new_test.png",
       width = 10,
       height = 10)
```
