---
title: "Bombus population genomics"
output: calculate_percentile_nsl.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:  
This script takes the output of selscan as input.  
The input consists of tab-delimited text files, one per bumblebee chromosome, which contains the following information:  
1) Locus ID (chromosome name)
2) Physical position
3) '1' Freq
4) ihs1
5) ihs0
6) Unstandardised ihs
7) Standardised ihs
8) Indicator of 'unsual' or not (1 = unsual; 0 = not)

```{r, message = FALSE}
## Load libraries; install from scratch if needed
libraries <- c("ggpubr", "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE )
    }
}
```
Read in file and calculate the top 1% value:

```{r, message = FALSE}
## Read in input file:
data <- read.table(file = "./combined_nsl_input_for_calculating_top_one.txt",
                   header = FALSE)

## Convert Standardised ihs to absolute values:
data$V7 <- abs(data$V7)

## Calculate top 1%:
nsl_quantile <- quantile(data$V7, 0.99)

## Assign name for output:
output <- "nsl_quantile.Rdata"

## Save:
save(nsl_quantile, file = output)
```
