---
title: "Bombus population genomics"
output: plot_sweed.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com 
---

## Introduction:
This scripts loads plots of composite likelihood ratio (CLR) values across genomic windows of 10kb as computed by SweeD for one single population of Bombus terrestris.

```{r, message = FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2", "ggpubr", "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE )
    }
}

## Create output directory:
dir.create("results")
```

Load input file:

```{r, message = FALSE}
summary_data <- read.table(file = "./SweeD_Report.test.txt",
                           header = TRUE)
```

Generate plots:

```{r, message = FALSE}
## Plot:
ggplot(summary_data, aes(x = Position,
                                       y = Likelihood)) +
        xlab("Genomic position (bp)") +
        ylab("Likelihood") +
        geom_point() +
        theme_bw()

```
