---
title: "Bombus population genomics"
output: supplemental_2_plot_ibs.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script loads an R object and plots a correlation plot of values estimated through an 'identity-by-descent' (IBD) analysis performed by [SNPRelate](https://bioconductor.org/packages/release/bioc/html/SNPRelate.html).
The output is a saved image (.png, .pdf) of a heatmap.

Load required libraries:

```{r, message = FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2",
               "reshape2",
               "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE)
    }
}
## Create output directory:
dir.create("results")
```

Load input file:

```{r, message = FALSE}
## Load R object:
load( file = "./results/pca_plots.Rdata")
```

Generate correlation plot:

```{r, message = FALSE}
## Updated column names:
colnames(input_for_melt) <- as.character(unlist(new_names))
rownames(input_for_melt) <- as.character(unlist(new_names))
input_for_melt_melted    <- melt(input_for_melt)

## Generate plot:
ibs_plot <- ggplot(data = input_for_melt_melted,
                   aes(x = Var1,
                       y = Var2,
                       fill = value)) +
        xlab("Samples") +
        ylab("Samples") +
        geom_tile(colour = "black") +
        theme(axis.text.x = element_text(angle = 90,
                                         hjust = 1),
              axis.title = element_text(size = 15,
                                        face = "bold")) +
        scale_fill_gradient(low = "yellow",
                            high = "black") +
        theme(axis.title = element_blank())

## Update legend title:
ibs_plot <- ibs_plot +
        guides(fill = guide_legend(title = "r value"))

## Print to console:
ibs_plot

## Save image as .png:
ggsave(file = "results/ibs_correlation_plot.png",
       height = 10,
       width = 10)

## Save image as .pdf:
ggsave(file = "results/ibs_correlation_plot.pdf",
       dpi = 600,
       height = 10,
       width = 10)
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "./supplemental_2_plot_ibs.Rmd")
```
