---
title: "Bombus population genomics"
output: combine_map_pca_plot.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script loads R objects containing:
1) A map of Britain detailing collection sites (highlighted by latitude);
2) A principal component analysis of sites (highlighted by landuse type)
3) A principal component analysis of sites (highlighted by latitude)

```{r, message = FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2",
               "ggpubr",
               "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE )
    }
}
## Create output directory:
dir.create("results")
```
Next step is to load input files (R objects)

```{r, message = FALSE}
## Load objects:
load(file = "./results/map_of_britain.Rdata")
load(file = "./results/pca_plots.Rdata")

## Correct the font size of axes:
lat_plot <- lat_plot + theme(axis.text = element_text(size = 10,
                                          face = "plain"),
                             axis.title = element_text(size = 15,
                                           face = "bold"))

## Combine and plot together:
ggarrange(britain_map,
          lat_plot,
          ncol = 2,
          nrow = 1,
          align = "hv",
          widths = c(1, 1),
          labels = c("A", "B"))

## Save combined plot to file:
ggsave(file = "./results/combined_plot.png",
        width = 15,
        height = 10)
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "./combine_plots.Rmd")

```
