---
title: "Bombus population genomics"
output: plot_pca.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

## Introduction:
This script loads R objects containing:
1) A principal component analysis of sites (highlighted by landuse type)
2) A principal component analysis of sites (highlighted by latitude)

```{r, message = FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2",
               "ggpubr",
               "ggrepel",
               "lintr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE)
    }
}
## Create output directory:
dir.create("results")
```
Next step is to load input files (R objects)

```{r, message = FALSE}
## Load objects:
load(file = "results/pca_plots.Rdata")
```

1. Plot PCA:

```{r, message = FALSE}
## Update latitude plot with points:
pca_plot <- ggplot(tab,
            aes(x = EV1,
                y = EV2)) +
            xlab(paste("Principal component ",
                       1,
                       " ",
                       "(",
                       round(pc_percent[1],
                             2), "%", ")",
                       sep = "")) +
            ylab(paste("Principal component ",
                       2,
                       " ",
                       "(",
                       round(pc_percent[2],
                             2), "%", ")",
                       sep = "")) +
        geom_point(size = 5,
                aes(color = latitude,
                    fill = latitude)) +
        geom_label_repel(aes(label = site_id)) +
        theme_minimal() +
            theme(axis.text = element_text(size = 10,
                  face = "plain"),
                  axis.title = element_text(size = 15,
                  face = "bold")) +
            theme(legend.position = "none")
```
Save output:

```{r, message = FALSE}
output_file_name <- "figure_1_pca"
## Create multiple image files:
for (extension in c("png",
                    "pdf")) {
         ## Create output path:
         path_to_dir <- paste("results/",
                              extension,
                              "/",
                              sep = "")
         ## Create output directory:
         dir.create(path = path_to_dir,
                    recursive = TRUE)
         ## Save:
         print(output_file_name)
         ggsave(file = paste(path_to_dir,
                             output_file_name,
                             ".",
                             extension,
                             sep = ""),
                dpi = 300,
                height = 20,
                width = 13)
}
```

Save also as an R object:

```{r, message = FALSE}
save.image(file = "results/pca_scatterplot_plot.RData")
```

Run lintr:

```{r, message = FALSE}
lintr::lint(file = "plot_pca.Rmd")
```
