---
title: "Bombus population genomics"
output: plot_global_sweeps.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE )
        }
}

## Create output folder:
dir.create(path = "./results/figures",
           recursive = TRUE)

```

Read in input data:

```{r, message = FALSE}
## Read in input file:
load(file = "./results/zscore_normalised.Rdata")

## Calculate mean:
nuc_div_mean <- mean(data$nuc_diversity)
data_td_sweep <- subset(data_td_sig, td_zscores < 0)
data_td_balancing <- subset(data_td_sig, td_zscores > 0)

## Subset significant sites for:
## 1) Nucleotide diversity
## 2) Tajima's D
## Turn off scientific notation:
options(scipen = 999)

## Generate a facet plot:
nuc_div_plot <- ggplot(data, aes(midpoint,
                                 nuc_diversity)) +
        xlab("Genomic coordinates (bp)") +
        ylab("Nucleotide diversity (pi)") +
        geom_point(colour = "black",
                           size = 1,
                           alpha = 0.1) +
        geom_hline(yintercept = nuc_div_mean,
                   linetype = "dashed",
                   colour = "orange") +
        geom_point(data = data_nd_sig, 
                           aes(x = midpoint,
                               y = nuc_diversity),
                           colour = "red",
                           size = 1,
                           alpha = 0.5) +
        geom_point(data = data_td_sweep, 
                           aes(x = midpoint,
                               y = nuc_diversity),
                           colour = "blue",
                           size = 1,
                           alpha = 0.5) +
        geom_point(data = data_td_balancing, 
                           aes(x = midpoint,
                               y = nuc_diversity),
                           colour = "green",
                           size = 1,
                           alpha = 0.5) +
        theme_bw() +
                theme(axis.text = element_text(size = 15),
              axis.title.x = element_text(size = 15,
                                          face = "bold"),
              axis.title.y = element_text(size = 15,
                                          face = "bold"),
              axis.text.y = element_text(size = 12,
                                         face = "bold"),
              axis.text.x = element_text(size = 12))

nuc_div_plot + facet_wrap( ~ chrom,
                           ncol = 2)

ggsave(file = "results/combined_nuc_div_across_chromomes.png",
       width = 10,
       height = 12)
```
