---
title: "Bombus population genomics"
output: plot_global_nucleotide_diversity.html
author: Joe Colgan, Yannick Wurm http://wurmlab.com
---

```{r, message = FALSE}
## Load libraries:
libraries <- c("lintr",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE )
        }
}

## Create output folder:
dir.create(path = "./results/figures",
           recursive = TRUE)

```

Read in input data:

```{r, message = FALSE}
## Read in input file:
data <- read.table(file = "./input/nucleotide_diversity_output/bter_all_chrom_10kb.txt",
                   header = TRUE)
## Calculate mean:
nuc_div_mean <- mean(data$nuc_diversity)

## Generate a facet plot:
nuc_div_plot <- ggplot(data, aes(midpoint,
                                 nuc_diversity)) +
        xlab("Genomic coordinates (bp)") +
        ylab("Nucleotide diversity (pi)") +
        geom_point(colour = "black",
                           size = 1,
                           alpha = 0.1) +
        geom_hline(yintercept = nuc_div_mean,
                   linetype = "dashed",
                   colour = "orange") +
        theme_bw()

nuc_div_plot + facet_wrap( ~ chrom,
                           ncol = 2)

ggsave(file = "results/combined_nuc_div_across_chromomes.png",
       width = 10,
       height = 15)
```
